	/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "main.h"
#include "main_1.h"

#include "software_timers.h"


//#define SYS_CORE_CLOCK	10000000	//	Parametr do SysTick,

/*
 * INFO:
 * 	-w celu poprawnego odpalenia pierwszego builda należało w plikach zakomentować:
 * 	stm32l4xx_ll_sdmmc.c --> linia 167 --> #include "stm32g4xx_hal.h"
 * 	stm32l4xx_ll_fmc.c --> linia 56 --> #include "stm32g4xx_hal.h"
 * 	main.c --> informacja o używaniu liczb zmiennoprzecinkowych,
 */

/*
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
*/

void MOTOR_DC_1(uint8_t data_read, DRV8833_t *pDRV8833);

int main(void)
{
	SetSysClk();
	SetSysCoreClock(SYS_CORE_CLOCK);
	SetSysTick(SYS_CORE_CLOCK);
	//LL_DBGMCU_SetTracePinAssignment(LL_DBGMCU_TRACE_ASYNCH);

	WS2812_init(&WS2812, 7);

	GPIO_set_pin_as_output(&TIM);
	GPIO_set_pin_as_output(&TEST_2);
	GPIO_set_pin_as_output(&TEST_3);
	GPIO_set_pin_as_output(&TEST_4);
	//TIM_one_pulse_mode();
	//TIM_one_pulse_mode_3();

	GPIO_set_pin_as_output(&LED_GREEN);
	GPIO_set_pin_as_input(&BUTTON_LINE);
	GPIO_set_pin_as_input(&LIMIT_SWITCH_X1_LINE);
	GPIO_set_pin_as_input(&LIMIT_SWITCH_X2_LINE);
	GPIO_set_pin_as_input(&DCF77_LINE);

	SM_init(&SM[0]);
	SM_init(&SM[1]);
	SM_init(&SM[2]);
	SERVO_init(&SERVO);



	//GPIO_set_pin_as_output(&WS2812_LINE);
	//TIM_basic_init(&WS2812_TIM);
	//TIM_mode_init(&WS2812_TIM_CH1);


	//LL_TIM_CC_EnableChannel(SM_1_CH.timer->TIMx, SM_1_CH.channel);	//	Wypuszczenie przebiegu na dany kanał,

	//USART_TX_Polling();
	//USART_TX_string(&USART_3, "led 1\n");


	//	KONFIGURACJA STEROWNIKA DRV8833:
	//GPIO_set_pin_as_output(&AIN1);
	//GPIO_set_pin_as_output(&AIN2);
	//GPIO_set_pin_as_output(&BIN1);
	//GPIO_set_pin_as_output(&BIN2);

	IRQ_init();
	EXTI2_X1_init();
	EXTI3_X2_init();
	EXTI_button_init();

	//DC_DRIVER_init(&MOTOR_1_DRIVER);
	//DRV8833_init(&DRIVER_2);
	//MOTOR_ride(&MOTOR_1, 70, CW_);

	//	AKTYWACJA INTERFEJSU UART2:
	GPIO_set_pin_as_output(&USART2_RX);
	GPIO_set_pin_as_output(&USART2_TX);
	USART_init(&USART_2);
	USART_start(&USART_2);
	USART_IT_conf(&USART_2);

	//	AKTYWACJA INTERFEJSU USART3:
	GPIO_set_pin_as_output(&USART3_RX);
	GPIO_set_pin_as_output(&USART3_TX);
	USART_init(&USART_3);
	USART_start(&USART_3);
	USART_IT_conf(&USART_3);

	//USART_TX_Polling();

	USART_TX_string(&USART_2, "led 1\n");
	//USART_TX_string(&USART_3, "led 1\n");
	//USART_TX_string(&USART_3, "led 1\n");

	//VT100_text("JESTEM");




	//TIM_start_counting(SM_1_CH.timer->TIMx);


	//GPIO_set_pin_as_output(SM_1_CH.line);	//	Konfiguracja linii z sygnałem PWM,
	//TIM_basic_init(SM_1_CH.timer);			//	Podstawowa konfiguracja zegara,
	//TIM_mode_init(&SM_1_CH);					//	Konfiguracja wybranego trybu pracy,


	//LL_TIM_EnableCounter(SM_1_CH.timer->TIMx);



	//	WŁĄCZENIE TERMINALA: wybór początkowego poprzez wartość 'terminal_ptr'
	TERMINAL_enable(TERM_DISP.terminal[TERM_DISP.terminal_ptr]);

	//	AKTYWACJA ADC POPRZEZ DMA:
	DMA_ADC1_init(&DMA_ADC);
	ADC_init_G4(&ADC_2);

#define H	32
#define L	16

	uint8_t color[5] = {0, 0, 1, 1, 1};
	/*
	uint8_t WS2812_ar[120] = {

			0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
			0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
			0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
			0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
			0, 0, 0, 0, 0, 0, 0, 0,

			L, L, L, L, L, H, H, H,
			L, L, L, L, L, L, L, L,
			L, L, L, L, L, L, L, L,

			L, L, L, L, L, L, L, L,
			L, L, L, L, L, H, H, H,
			L, L, L, L, L, L, L, L,

			L, L, L, L, L, L, L, L,
			L, L, L, L, L, L, H, H,
			L, L, L, L, L, L, L, L,
	};

*/


	//DMA_TIM8_CH1.ptr_8 = (uint8_t*)&WS2812_ar[0];
	//DMA_TIM8_CH1.number_of_data = 120 + 48 + 48;

	WS2812_fill_line(WS2812_LED_LINE, WS2812_LED_LINE_DATA, 7);

	DMA_TIMx_CHx_init(&DMA_TIM8_CH1);
	DMA_start(&DMA_TIM8_CH1);

	GPIO_toggle_pin(&TIM);
	TIM_start_counting(TIM8);
	GPIO_toggle_pin(&TIM);

	while(1)
	{
		//USART_TX_string(&USART_2, "led 1\n");
		//	====================================================
		//	OBSŁUGA NOWO ODEBRANYCH DANYCH PO USART Z TERMINALA:
		//	====================================================
		if(USART_get_flag_new_data(&USART_2) == 1)
		{
			uint8_t data_read = USART_get_data(&USART_2);	//	Pobranie ostatnio odebranej danej,

			for(uint8_t i = '1'; i<='9'; i++)
			{
				if(data_read == i)
				{
					if((data_read - 49) != TERMINAL_get_terminal(&TERM_DISP))
					{
						//	PRZEŁĄCZENIE NA NOWY TERMINAL:
						//SM_set_standby(&SM[TERM_DISP.terminal_ptr]);
						TERMINAL_change(TERM_DISP.terminal[TERM_DISP.terminal_ptr], TERM_DISP.terminal[data_read - 49]);
						TERMINAL_set_terminal(&TERM_DISP, data_read);
						TERMINAL_main_title(TERM_DISP.terminal[TERM_DISP.terminal_ptr], TERM_DISP.terminal[TERM_DISP.terminal_ptr]->name);
						USART_reset_flag_new_data(&USART_2);
					}
				}
			}
		}

		//	WEJŚCIE DO MENU ZALEŻNEGO OD WYBRANEGO TERMINALA:
		if(TERM_DISP.foo_menu[TERM_DISP.terminal_ptr] != NULL)
		{
			TERM_DISP.foo_menu[TERM_DISP.terminal_ptr]();
		}
	}
}



void MOTOR_DC_1(uint8_t data_read, DRV8833_t *pDRV8833)
{

	if(data_read == 'q')
	{
		DRV8833_idle(pDRV8833);
	}
	else if(data_read == 'e')
	{
		DRV8833_brake(pDRV8833);
	}
	//	################################################################
	else if(data_read == '1')
	{
		DRV8833_idle(pDRV8833);
		TERMINAL_change(&TERMINAL_DC, &TERMINAL_BASE);
	}
	//	################################################################
	else if(data_read == 'r')
	{
		DRV8833_inc_dec_value(pDRV8833, 1);
	}
	//	################################################################
	else if(data_read == 'z')
	{
		DRV8833_ride(pDRV8833, 0, REVERSE_IDLE);
	}
	else if(data_read == 'x')
	{
		DRV8833_ride(pDRV8833, 0, FORWARD_IDLE);
	}
	else if(data_read == 'c')
	{
		DRV8833_ride(pDRV8833, LL_TIM_GetAutoReload(pDRV8833->tim_mode_1->timer->TIMx) + 1, REVERSE_BRAKE);
	}
	else if(data_read == 'v')
	{
		DRV8833_ride(pDRV8833, LL_TIM_GetAutoReload(pDRV8833->tim_mode_1->timer->TIMx) + 1, FORWARD_BRAKE);
	}
	//	################################################################
	else if(data_read == 'm')
	{
		DRV8833_ride(pDRV8833, LL_TIM_GetAutoReload(pDRV8833->tim_mode_1->timer->TIMx) + 1, FORWARD_IDLE);
	}
	//	################################################################
	else if(data_read == 'w')
	{
		DRV8833_inc_dec(pDRV8833, DRV8833_inc_dec_value(pDRV8833, 0));
	}
	else if(data_read == 's')
	{
		DRV8833_inc_dec(pDRV8833, -DRV8833_inc_dec_value(pDRV8833, 0));
	}
	//	################################################################
	else if(data_read == 'a')
	{
		DRV8833_ride(pDRV8833, 500, FORWARD_IDLE);
		delay_ms(200);
		DRV8833_brake(pDRV8833);
	}
	else if(data_read == 'd')
	{
		DRV8833_ride(pDRV8833, 500, REVERSE_IDLE);
		delay_ms(200);
		DRV8833_brake(pDRV8833);
	}
	//	################################################################
	else if(data_read == 'p')
	{
		for(uint16_t i = 200; i<LL_TIM_GetAutoReload(pDRV8833->tim_mode_1->timer->TIMx) + 1; i++)
		{
			DRV8833_ride(pDRV8833, i, REVERSE_IDLE);
			delay_ms(10);
		}
		for(uint16_t i = LL_TIM_GetAutoReload(pDRV8833->tim_mode_1->timer->TIMx) + 1; i>200; i--)
		{
			DRV8833_ride(pDRV8833, i + 1, REVERSE_IDLE);
			delay_ms(10);
		}
		for(uint16_t i = 200; i<LL_TIM_GetAutoReload(pDRV8833->tim_mode_1->timer->TIMx) + 1; i++)
		{
			DRV8833_ride(pDRV8833, i, REVERSE_IDLE);
			delay_ms(2);
		}
		for(uint16_t i = LL_TIM_GetAutoReload(pDRV8833->tim_mode_1->timer->TIMx) + 1; i>200; i--)
		{
			DRV8833_ride(pDRV8833, i + 1, REVERSE_IDLE);
			delay_ms(2);
		}

		for(uint8_t j = 0; j<10; j++)
		{
			for(uint16_t i = 200; i<LL_TIM_GetAutoReload(pDRV8833->tim_mode_1->timer->TIMx) + 1; i++)
			{
				DRV8833_ride(pDRV8833, i, REVERSE_IDLE);
				delay_ms(1);
			}
			for(uint16_t i = LL_TIM_GetAutoReload(pDRV8833->tim_mode_1->timer->TIMx) + 1; i>200; i--)
			{
				DRV8833_ride(pDRV8833, i + 1, REVERSE_IDLE);
				delay_ms(1);
			}
		}

		DRV8833_brake(pDRV8833);
	}
}



/*
if(USART_get_flag_new_data(&USART_2) == 1)
{
	uint8_t data_read = USART_get_data(&USART_2);	//	Pobranie ostatnio odebranej danej,

	for(uint8_t i = '1'; i<='4'; i++)
	{
		if(data_read == i)
		{
			if(TERMINAL_BASE.menu != NULL)
			{
				TERMINAL_change(&TERMINAL_BASE, &TERMINAL_SM);
			}

			SM_set_standby(&SM[TERMINAL_SM.instance]);
			TERMINAL_SM.instance = i - 49;
			TERMINAL_SM.name = &(SM[TERMINAL_SM.instance].description[0]);
			TERMINAL_main_title(&TERMINAL_SM, TERMINAL_SM.name);
			USART_reset_flag_new_data(&USART_2);
			break;
		}
	}
	if(data_read == '0')
	{
		if(TERMINAL_SM.menu != NULL)
		{
			SM_set_standby(&SM[TERMINAL_SM.instance]);
			TERMINAL_change(&TERMINAL_SM, &TERMINAL_BASE);
			TERMINAL_main_title(&TERMINAL_BASE, TERMINAL_BASE.name);
			USART_reset_flag_new_data(&USART_2);
		}
	}
	if(data_read == '9')
	{
		if(TERMINAL_SM.menu != NULL)
		{
			SM_set_standby(&SM[TERMINAL_SM.instance]);
			TERMINAL_change(&TERMINAL_SM, &TERMINAL_SONGS);
			TERMINAL_main_title(&TERMINAL_SONGS, TERMINAL_SONGS.name);
			USART_reset_flag_new_data(&USART_2);
		}
	}
	if(data_read == '8')
	{
		if(TERMINAL_SM.menu != NULL)
		{
			SM_set_standby(&SM[TERMINAL_SM.instance]);
			TERMINAL_change(&TERMINAL_SM, &TERMINAL_SERVO);
			TERMINAL_main_title(&TERMINAL_SERVO, TERMINAL_SERVO.name);
			USART_reset_flag_new_data(&USART_2);
		}
	}
	if(data_read == '7')
	{
		if(TERMINAL_SM.menu != NULL)
		{
			SM_set_standby(&SM[TERMINAL_SM.instance]);
			TERMINAL_change(&TERMINAL_SM, &TERMINAL_ADC);
			TERMINAL_main_title(&TERMINAL_ADC, TERMINAL_ADC.name);
			USART_reset_flag_new_data(&USART_2);
		}
	}
}
*/





/*
		//	////////////////////////////////////////////////////////////////////
		//	OBSŁUGA NOWO ODEBRANYCH DANYCH PO USART Z TERMINALA:
		if((USART_get_flag_new_data(&USART_2) == 1) && (TERMINAL_DC.menu != NULL))
		{
			USART_reset_flag_new_data(&USART_2);
			uint8_t data_read = USART_get_data(&USART_2);	//	Pobranie ostatnio odebranej danej,

			//MOTOR_DC_1(data_read, &DRIVER_2);

			if(data_read == 'q')
			{
				DRV8833_idle(&DRIVER_1);
			}
			else if(data_read == 'e')
			{
				DRV8833_brake(&DRIVER_1);
			}
			//	################################################################
			else if(data_read == '1')
			{
				DRV8833_idle(&DRIVER_1);
				TERMINAL_change(&TERMINAL_DC, &TERMINAL_BASE);
			}
			//	################################################################
			else if(data_read == 'r')
			{
				DRV8833_inc_dec_value(&DRIVER_1, 1);
			}
			//	################################################################
			else if(data_read == 'z')
			{
				if(DRV8833_get_driver_state(&DRIVER_1) != REVERSE_IDLE)
				{
					DRV8833_ride(&DRIVER_1, 0, REVERSE_IDLE);
				}
			}
			else if(data_read == 'x')
			{
				if(DRV8833_get_driver_state(&DRIVER_1) != REVERSE_BRAKE)
				{
					DRV8833_ride(&DRIVER_1, 0, REVERSE_BRAKE);
				}
			}
			else if(data_read == 'c')
			{
				//DRV8833_ride(&DRIVER_1, LL_TIM_GetAutoReload(DRIVER_1.tim_mode_1->timer->TIMx) + 1, FORWARD_IDLE);
				DRV8833_ride(&DRIVER_1, 0, FORWARD_IDLE);
			}
			else if(data_read == 'v')
			{
				//DRV8833_ride(&DRIVER_1, LL_TIM_GetAutoReload(DRIVER_1.tim_mode_1->timer->TIMx) + 1, FORWARD_BRAKE);
				DRV8833_ride(&DRIVER_1, 0, FORWARD_BRAKE);
			}
			//	################################################################
			else if(data_read == 'm')
			{
				DRV8833_ride(&DRIVER_1, LL_TIM_GetAutoReload(DRIVER_1.tim_mode_1->timer->TIMx) + 1, FORWARD_IDLE);
			}
			//	################################################################
			else if(data_read == 'w')
			{
				//DRV8833_inc_dec(&DRIVER_1, DRV8833_inc_dec_value(&DRIVER_1, 0));
			}
			else if(data_read == 's')
			{
				DRV8833_inc_dec(&DRIVER_1, -DRV8833_inc_dec_value(&DRIVER_1, 0));
			}
			//	################################################################
			else if(data_read == 'a')
			{
				DRV8833_ride(&DRIVER_1, 500, FORWARD_IDLE);
				delay_ms(200);
				DRV8833_brake(&DRIVER_1);
			}
			else if(data_read == 'd')
			{
				DRV8833_ride(&DRIVER_1, 500, REVERSE_IDLE);
				delay_ms(200);
				DRV8833_brake(&DRIVER_1);
			}
			//	################################################################
			else if(data_read == 'p')
			{
				for(uint16_t i = 200; i<LL_TIM_GetAutoReload(DRIVER_1.tim_mode_1->timer->TIMx) + 1; i++)
				{
					DRV8833_ride(&DRIVER_1, i, REVERSE_IDLE);
					delay_ms(10);
				}
				for(uint16_t i = LL_TIM_GetAutoReload(DRIVER_1.tim_mode_1->timer->TIMx) + 1; i>200; i--)
				{
					DRV8833_ride(&DRIVER_1, i + 1, REVERSE_IDLE);
					delay_ms(10);
				}
				for(uint16_t i = 200; i<LL_TIM_GetAutoReload(DRIVER_1.tim_mode_1->timer->TIMx) + 1; i++)
				{
					DRV8833_ride(&DRIVER_1, i, REVERSE_IDLE);
					delay_ms(2);
				}
				for(uint16_t i = LL_TIM_GetAutoReload(DRIVER_1.tim_mode_1->timer->TIMx) + 1; i>200; i--)
				{
					DRV8833_ride(&DRIVER_1, i + 1, REVERSE_IDLE);
					delay_ms(2);
				}

				for(uint8_t j = 0; j<10; j++)
				{
					for(uint16_t i = 200; i<LL_TIM_GetAutoReload(DRIVER_1.tim_mode_1->timer->TIMx) + 1; i++)
					{
						DRV8833_ride(&DRIVER_1, i, REVERSE_IDLE);
						delay_ms(1);
					}
					for(uint16_t i = LL_TIM_GetAutoReload(DRIVER_1.tim_mode_1->timer->TIMx) + 1; i>200; i--)
					{
						DRV8833_ride(&DRIVER_1, i + 1, REVERSE_IDLE);
						delay_ms(1);
					}
				}

				DRV8833_brake(&DRIVER_1);
			}
		}
*/







